Repository Software-Projekt-Thiel-2020/Frontend, pull requests merged in 2020-06, with the labels that each got.

#67 Fix router link for "Jetzt spenden!" button
  src/components/pages/Home.vue
Labels: bug

#68 Navbar merge
  src/components/elements/Navbar.vue
Labels: good first issue

#78 Firmenname: entfernt
  src/components/pages/Gutscheine.vue
  src/components/pages/Spenden.vue
Labels: enhancement

#77 Navbar fix
  src/components/elements/Navbar.vue
Labels: enhancement
