Repository Software-Projekt-Thiel-2020/Frontend, pull requests merged in 2020-08, with the labels that each got.

#148 Errorhandling/Seitebenutzbarkeit
  src/components/pages/Portfolio.vue
  src/components/pages/ProjektAnlegen.vue
  src/components/pages/ProjektEditieren.vue
Labels: enhancement

#147 Navbar Snackbar button now closeable
  src/components/elements/Navbar.vue
Labels: bug

#141 Institution card fix
  src/components/pages/Gutscheine.vue
  src/components/pages/Spenden.vue
Labels: bug, enhancement

#196 added map.setView()
  src/components/pages/InstitutionEditieren.vue
  src/components/pages/ProjektEditieren.vue
Labels: enhancement

#205 Profil design refactor
  src/components/Default.vue
  src/components/pages/BenutzerProfil.vue
Labels: enhancement

#216 Small fixes
  src/App.vue
  src/assets/blockstack.svg
  src/components/elements/Footer.vue
  src/components/pages/AGB.vue
  src/components/pages/Datenschutz.vue
  src/components/pages/Gutscheine.vue
  src/components/pages/Home.vue
  src/components/pages/InstitutionVoucher.vue
  src/components/pages/Portfolio.vue
  src/components/pages/Project.vue
  src/components/pages/ProjectGutschein.vue
  src/components/pages/ProjektEditieren.vue
  src/components/pages/Spenden.vue
  src/components/pages/WarumSpenden.vue
Labels: enhancement
